# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_DATABASE: shaka_test
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -proot || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      # Match your .env.test values
      NODE_ENV: test
      FRONT_API_BASE_URL: http://localhost:5173
      DATABASE_URL: mysql://root:root@127.0.0.1:3306/shaka_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Copy .env.test for runtime (optional)
        run: cp .env.test .env || true

      - name: Wait for MySQL (TCP)
        shell: bash
        run: |
          for i in {1..60}; do
            (echo > /dev/tcp/127.0.0.1/3306) >/dev/null 2>&1 && echo "MySQL is up" && break
            echo "Waiting for MySQL... ($i/60)"
            sleep 2
          done

      # If you need Prisma migrations, run them here (commented if handled by shakadb already)
      # - name: Run Prisma migrations
      #   run: npx prisma migrate deploy

      - name: Seed test DB
        run: npm run seed:test

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Unit tests
        run: npm run test

      - name: E2E tests
        run: npm run test:e2e
